{% set name = "awk" %}
{% set version = "20251225" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/onetrueawk/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 626d7d19f8e4ceae70f60e2e662291789e0f54ab86945317a3d5693c30f847a2

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - make
    - bison
  run_constrained:
    - gawk <0a0

test:
  commands:
    - awk 'BEGIN {print 1+1}'

about:
  home: https://github.com/onetrueawk/awk
  license: LicenseRef-Lucent-Technologies
  license_file: LICENSE
  summary: One true awk
  description: |
    This is the version of awk described in The AWK Programming Language, Second
    Edition, by Al Aho, Brian Kernighan, and Peter Weinberger (Addison-Wesley,
    2024, ISBN-13 978-0138269722, ISBN-10 0138269726).
  dev_url: https://github.com/onetrueawk/awk

extra:
  recipe-maintainers:
    - apcamargo
